INSTRUCTIONS:

Go to File -> Save a Copy in Drive and edit this notebook in your copy

Name the copy as : Name_RollNo_AssignmentNo

Put all your doubts on Whatsapp group.

try not to use chatgpt

In [ ]:
import numpy as np

1.Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
y = np.ones(4)
y

array([1., 1., 1., 1.])

2.Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [ ]:
X = np.array([[1, 2], [3, 4]])
y = np.matrix(X)
print(y)

[[1 2]
 [3 4]]


3.Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [ ]:
x= np.linspace(3, 10, 50)
x

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

4.Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])

ans = x.reshape(-1,order='F')
ans

array([1, 4, 2, 5, 3, 6])

5.Compute the inverse and primary diagnol sum of x=[[1,2],[3,4]]

In [ ]:
x = np.array([[1, 2],
              [3, 4]])
a=np.trace(x)
print(a)
invx = np.linalg.inv(x)
print(invx)

5
[[-2.   1. ]
 [ 1.5 -0.5]]


7.Sort x along the second axis. x = [[1,4],[3,1]]

In [ ]:
x = np.array([[1, 4],
              [3, 1]])

y = np.sort(x, axis=1)
print(y)


[[1 4]
 [1 3]]


8.Get the indices that would sort x(as above) along the second axis.

In [ ]:
idx = np.argsort(x, axis=1)
print(idx)

[[0 1]
 [1 0]]


 9.Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
x = np.random.rand(2, 5) * 10
x

array([[9.86485141, 3.14257198, 8.05990656, 5.38175257, 7.73953358],
       [1.49204487, 0.98129201, 7.3146572 , 9.25818984, 4.32694385]])

In [ ]:
max_value = np.amax(x, axis=1)
min_value = np.amin(x, axis=1)
print(max_value)
print(min_value)
idx1=np.argmax(x, axis=1)
idx2=np.argmin(x, axis=1)
print(idx1)
print(idx2)


[9.86485141 9.25818984]
[3.14257198 0.98129201]
[0 3]
[1 1]


10.You're tasked with analyzing data from a space exploration mission. The data is stored in a numpy array distances representing the distances (in light-years) of various stars from Earth.

Your task is to complete the code by implementing numpy functions to accomplish the tasks outlined in the comments. Ensure that your code is concise, efficient, and produces accurate results.

In [ ]:
# Array of distances to stars (in light-years)
x = np.array([10.2, 20.5, 15.8, 30.1, 25.6])

# Task 1: Find the average distance to the stars.
# Task 2: Identify the star(s) closest to Earth.
# Task 3: Calculate the total distance traveled if a spaceship were to visit each star and return to Earth.
# Task 4: Determine if there are any stars beyond a certain threshold distance (e.g., 25 light-years).
#1
avg = np.mean(x)
print(avg)
#2
x1=np.amin(x)
print(x1)
#3
x2=np.sum(x)
print(2*x2)
#4
flag=0
for i in range(np.size(x)):
  if(x[i]>25):
    print("yes")
    flag=1
    break
if(flag==0): print("no")
# Your code here...

20.439999999999998
10.2
204.39999999999998
yes
